<?php

    $reasonMessage= '';
    switch ($this->reason) {
    case \Zend\Mvc\Application::ERROR_CONTROLLER_CANNOT_DISPATCH:
        $reasonMessage = $this->translate('The requested controller was unable to dispatch the request.');
        break;
    case \Zend\Mvc\Application::ERROR_CONTROLLER_NOT_FOUND:
        $reasonMessage = $this->translate('The requested controller could not be mapped to an existing controller class.');
        break;
    case \Zend\Mvc\Application::ERROR_CONTROLLER_INVALID:
        $reasonMessage = $this->translate('The requested controller was not dispatchable.');
        break;
    case \Zend\Mvc\Application::ERROR_ROUTER_NO_MATCH:
        $reasonMessage = $this->translate('The requested URL could not be matched by routing.');
        break;
    default:
        $reasonMessage = $this->translate('We cannot determine at this time why a 404 was generated.');
        break;
    }

?>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1><?= $this->translate('A 404 error occurred') ?></h1>
            <h3><?= $this->message ?></h3>
        </div>
    </div>

    <?php if (isset($this->reason) && $this->reason): ?>
        <div class="row">
            <div class="col-lg-12">
                <p><?=$reasonMessage ?></p>

                <?php if (isset($this->controller) && $this->controller): ?>
                    <dl>
                        <dt><?= $this->translate('Controller') ?>:</dt>
                        <dd><?=$this->escapeHtml($this->controller) ?></dd>
                        <dt><?= $this->translate('Controller class') ?>:</dt>
                        <dd>
                            <?php if (isset($this->controller_class)): ?>
                                <?= $this->escapeHtml($this->controller) ?>
                            <?php endif ?>
                        </dd>
                    </dl>
                <?php endif ?>
            </div>
        </div>
    <?php endif ?>

    <?php if (!isset($this->display_exceptions) || !$this->display_exceptions) return; ?>

    <div class="row">
        <div class="col-lg-12">
            <?php if (!isset($this->exception) || !$this->exception instanceof Exception): ?>
                <h3><?= $this->translate('No Exception available') ?></h3>
            <?php else: ?>
                <?php $e = $this->exception; while ($e): ?>
                    <h3><?= get_class($e) ?></h3>
                    <dl>
                        <dt><?= $this->translate('File') ?>:</dt>
                        <dd>
                            <pre><?= $e->getFile() ?>:<?= $e->getLine() ?></pre>
                        </dd>
                        <dt><?= $this->translate('Message') ?>:</dt>
                        <dd>
                            <pre><?= $e->getMessage() ?></pre>
                        </dd>
                        <dt><?=$this->translate('Stack trace') ?>:</dt>
                        <dd>
                            <pre><?= $e->getTraceAsString() ?></pre>
                        </dd>
                    </dl>
                <?php $e = $e->getPrevious(); endwhile ?>
            <?php endif ?>
        </div>
    </div>
</div>
