<script>
    function printDateTime(timestamp) {
        if (timestamp == null)
            return;

        var local = moment.unix(timestamp).local();
        document.write(local.format('YYYY-MM-DD HH:mm:ss Z'));
    }

    function editDocumentForm(id) {
        $.ajax({
            url: '<?= $this->basePath('/example-odm/index/edit-form') ?>',
            data: {
                id: id
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text(
                    typeof id == 'undefined'
                        ? '<?= $this->translate('Create document') ?>'
                        : '<?= $this->translate('Edit document') ?>'
                );
                modal.find('button[type=submit]').text(
                    typeof id == 'undefined'
                        ? '<?= $this->translate('Create') ?>'
                        : '<?= $this->translate('Save changes') ?>'
                );
                modal.find('.modal-body').html(html);
            }
        });
    }

    function deleteDocumentForm(id) {
        $.ajax({
            url: '<?= $this->basePath('/example-odm/index/delete-form') ?>',
            data: {
                id: id
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Delete document') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Delete') ?>');
                modal.find('.modal-body').html(html);
            }
        });
    }
</script>

<div id="modal-form" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <img src="<?= $this->basePath('/img/loader.gif') ?>" class="spinner">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <?= $this->translate('Cancel') ?>
                </button>
                <button type="submit" class="btn btn-primary">
                    <?= $this->translate('Submit') ?>
                </button>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1><?= $this->translate('Documents &amp; Form Example') ?></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <button class="btn btn-default" onclick="editDocumentForm()">
                <?= $this->translate('Create document') ?>
            </button>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th><?= $this->translate('String') ?></th>
                        <th><?= $this->translate('Integer') ?></th>
                        <th><?= $this->translate('Float') ?></th>
                        <th><?= $this->translate('Boolean') ?></th>
                        <th><?= $this->translate('DateTime') ?></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->documents as $document): ?>
                        <tr>
                            <td><?= $document->getId() ?></td>
                            <td><?= $this->escapeHtml($document->getValueString()) ?></td>
                            <td><?= \Application\Tool\Number::localeFormat($document->getValueInteger()) ?></td>
                            <td><?= \Application\Tool\Number::localeFormat($document->getValueFloat()) ?></td>
                            <td>
                                <?php
                                    $b = $document->getValueBoolean();
                                    if ($b !== null)
                                        echo $this->translate($b ? 'true' : 'false')
                                ?>
                            </td>
                            <td>
                                <script>
                                    printDateTime(<?= ($dt = $document->getValueDatetime()) ? $dt->getTimestamp() : 'null' ?>);
                                </script>
                            </td>
                            <td style="width: 1px; white-space: nowrap;">
                                <button type="button" class="btn btn-default btn-xs"
                                        onclick="editDocumentForm('<?= $document->getId() ?>')">
                                    <?= $this->translate('Edit') ?>
                                </button>
                                <button type="button" class="btn btn-default btn-xs"
                                        onclick="deleteDocumentForm('<?= $document->getId() ?>')">
                                    <?= $this->translate('Delete') ?>
                                </button>
                            </td>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <h4>Note on number fields</h4>
            <p>Integer and float fields are printed according to current locale (thousand and decimal separators)</p>
        </div>
    </div>
</div>
