<?= $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->translate('APP_TITLE'))
                 ->setSeparator(' - ')
                 ->setAutoEscape(false) ?>

<?= $this->headMeta()
         ->appendName('viewport', 'width=device-width, initial-scale=1.0')
         ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
         ->toString(8) ?>

<?php if (@$_ENV['ENVIRONMENT'] == 'development'): ?>

    <?= $this->headLink([
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath('/img/favicon.ico')
               ])
             ->prependStylesheet($this->basePath('/css/app.css'))
             ->prependStylesheet($this->basePath('/css/vendor.css'))
             ->toString(8) ?>
     
    <?= $this->headScript()
             ->prependFile($this->basePath('/js/app.js'))
             ->prependFile($this->basePath('/js/vendor.js'))
             ->toString(8) ?>

<?php else: // Production ?>

    <?= $this->headLink([
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath('/img/favicon.ico')
               ])
             ->prependStylesheet($this->basePath('/css/app.min.css'))
             ->prependStylesheet($this->basePath('/css/vendor.min.css'))
             ->toString(8) ?>
     
    <?= $this->headScript()
             ->prependFile($this->basePath('/js/app.min.js'))
             ->prependFile($this->basePath('/js/vendor.min.js'))
             ->toString(8) ?>

<?php endif ?>

    </head>
    <body>

<?= $this->content; ?>

<?= $this->inlineScript() ?>

    </body>
</html>
