<?= $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->translate('APP_TITLE'))
                 ->setSeparator(' - ')
                 ->setAutoEscape(false) ?>

<?= $this->headMeta()
         ->appendName('viewport', 'width=device-width, initial-scale=1.0')
         ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
         ->toString(8) ?>

<?php if (@$_ENV['ENVIRONMENT'] == 'development'): ?>

    <?= $this->headLink([
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath('/img/favicon.ico')
               ])
             ->prependStylesheet($this->basePath('/css/app.css'))
             ->prependStylesheet($this->basePath('/css/vendor.css'))
             ->toString(8) ?>
     
    <?= $this->headScript()
             ->prependFile($this->basePath('/js/app.js'))
             ->prependFile($this->basePath('/js/vendor.js'))
             ->toString(8) ?>

<?php else: // Production ?>

    <?= $this->headLink([
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath('/img/favicon.ico')
               ])
             ->prependStylesheet($this->basePath('/css/app.min.css'))
             ->prependStylesheet($this->basePath('/css/vendor.min.css'))
             ->toString(8) ?>
     
    <?= $this->headScript()
             ->prependFile($this->basePath('/js/app.min.js'))
             ->prependFile($this->basePath('/js/vendor.min.js'))
             ->toString(8) ?>

<?php endif ?>

    </head>
    <body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#layout-navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="javascript:void(0)"><?= $this->translate('APP_TITLE') ?></a>
            </div>

            <div class="collapse navbar-collapse" id="layout-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <?php $short = substr($this->locale['current'], 0, 2); ?>
                            <img src="<?= $this->basePath('/img/flags/' . $short . '.gif') ?>">
                            <?= $short ?>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <?php foreach ($this->locale['available'] as $locale): ?>
                                <li>
                                    <a href="javascript:void(0)" onclick="$.cookie('locale', '<?= $locale ?>', { path: '/' }); window.location.reload()">
                                        <span class="glyphicon glyphicon-ok <?= $this->locale['cookie'] == $locale ?: 'invisible' ?>"></span>
                                        <?= $this->translate($locale) ?>
                                    </a>
                                </li>
                            <?php endforeach ?>
                            <li class="divider"></li>
                            <li>
                                <a href="javascript:void(0)" onclick="$.removeCookie('locale', { path: '/' }); window.location.reload()">
                                    <span class="glyphicon glyphicon-ok <?= $this->locale['cookie'] == '' ?: 'invisible' ?>"></span>
                                    <?= $this->translate('Autodetect') ?>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

<?= $this->content; ?>

<?= $this->inlineScript() ?>

    </body>
</html>
