<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentSampleHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['value_string'])) {
            $value = $data['value_string'];
            $return = (string) $value;
            $this->class->reflFields['value_string']->setValue($document, $return);
            $hydratedData['value_string'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['value_integer'])) {
            $value = $data['value_integer'];
            $return = (int) $value;
            $this->class->reflFields['value_integer']->setValue($document, $return);
            $hydratedData['value_integer'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['value_float'])) {
            $value = $data['value_float'];
            $return = (float) $value;
            $this->class->reflFields['value_float']->setValue($document, $return);
            $hydratedData['value_float'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['value_boolean'])) {
            $value = $data['value_boolean'];
            $return = (bool) $value;
            $this->class->reflFields['value_boolean']->setValue($document, $return);
            $hydratedData['value_boolean'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['value_datetime'])) {
            $value = $data['value_datetime'];
            if ($value instanceof \MongoDate) { $return = new \DateTime(); $return->setTimestamp($value->sec); } elseif (is_numeric($value)) { $return = new \DateTime(); $return->setTimestamp($value); } elseif ($value instanceof \DateTime) { $return = $value; } else { $return = new \DateTime($value); }
            $this->class->reflFields['value_datetime']->setValue($document, clone $return);
            $hydratedData['value_datetime'] = $return;
        }
        return $hydratedData;
    }
}