#!/bin/sh

run_command() {
    $@
    if [ $? -ne 0 ]; then
        exit 2
    fi
}

if [ "$1" != "dev" -a "$1" != "prod" ]; then
    echo "Usage: $0 dev|prod"
    exit 1
fi

cd front

if [ $1 == "prod" ]; then
    run_command ./node_modules/.bin/grunt prod
    exit 0
fi

run_command ./node_modules/.bin/grunt dev 
