#!/bin/sh

run_command() {
    $@
    if [ $? -ne 0 ]; then
        exit 2
    fi
}

if [ "$1" != "dev" -a "$1" != "prod" ]; then
    echo "Usage: $0 dev|prod"
    exit 1
fi


if [ "$1" == "dev" ]; then
    run_command php composer.phar self-update
    run_command php composer.phar update
elif [ $1 == "prod" ]; then
    run_command php composer.phar --no-dev install
fi
