#!/bin/sh

echo "=> Deleting Example module directory"
rm -rf module/ExampleORM
rm -rf module/ExampleODM

echo "=> Updating application.config.php"
sed -i '' "/'ExampleORM'/d" config/application.config.php
sed -i '' "/'ExampleODM'/d" config/application.config.php

echo "=> Removing Sample entity and repository"
rm -f "module/Application/src/Application/Entity/Sample.php"
rm -f "module/Application/src/Application/Entity/SampleRepository.php"
rm -f "module/Application/test/ApplicationTest/Entity/SampleRepositoryTest.php"

echo "=> Removing Sample document and repository"
rm -f "module/Application/src/Application/Document/Sample.php"
rm -f "module/Application/src/Application/Document/SampleRepository.php"

echo "=> Updating PHPUnit config"
sed -i '' "/'ExampleORM'/d" test/Bootstrap.php
sed -i '' "/'ExampleORMTest'/d" test/Bootstrap.php
sed -i '' "/'ExampleODM'/d" test/Bootstrap.php
sed -i '' "/'ExampleODMTest'/d" test/Bootstrap.php
sed -i '' "/module\/ExampleORM\/test\/ExampleORMTest/d" test/phpunit.xml.dist
sed -i '' "/module\/ExampleODM\/test\/ExampleODMTest/d" test/phpunit.xml.dist

echo
echo -n "==> Do you want to clear app.js and app.css? [y/n] "
read input

if [ "$input" = "y" ]; then
    echo "=> Emptying app.js and app.css"
    rm -f front/js/app.js
    touch front/js/app.js
    rm -f front/css/app.css
    touch front/css/app.css
fi

echo
echo "All done. Remove database schema and rewrite console action populate-db yourself"
