#!/bin/sh

run_command() {
    $@
    if [ $? -ne 0 ]; then
        exit 2
    fi
}

if [ "$1" != "dev" -a "$1" != "prod" ]; then
    echo "Usage: $0 dev|prod"
    exit 1
fi

if [ $1 == "prod" ]; then
    run_command php composer.phar --no-dev install
    exit 0
fi

which npm > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "Please install node.js and npm"
    exit 3
fi

run_command php composer.phar self-update
run_command php composer.phar update
cd front
run_command npm update 
run_command node_modules/.bin/bower update
